jwt:
  signerKey: "EIG2ryG3InsGo7mStNgivMrw2/OpHD4UrBJUPwkSWacWJaEztRuqsr/axSiuCTxZ"

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:djpmekvyd}
  api_key: ${CLOUDINARY_API_KEY:486573992241243}
  api_secret: ${CLOUDINARY_API_SECRET}

local:
  storage:
    path: "D:\\file_activity_repo"

server:
  host: "http://localhost:8000/AMQNU/api"

rate-limit:
  enabled: ${RATE_LIMIT_ENABLED:true}
